---
services:
  - docker:19.03-dind

variables:
  DOCKER_IMAGE_NAME: lansible/nexe

include:
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-login.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-build.yml

stages:
  - build
  - test
  - publish
