---
variables:
  DOCKER_IMAGE_NAME: lansible/nexe

include:
  - template: Container-Scanning.gitlab-ci.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/dev/docker-login.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/dev/docker-build.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/dev/sast-cis-benchmark.yml

stages:
  - build
  - test
  - push
  - manifest
